/**
 * Curated library of real, verified learning resources.
 * URLs are direct links — no search redirects.
 */

export type LibraryResource = {
  id: string;
  title: string;
  creator: string;
  platform: "YouTube" | "Coursera" | "Certification" | "Free" | "Udemy" | "GitHub";
  url: string;
  is_free: boolean;
  duration_hint: string;
  type: "video" | "course" | "certification" | "project" | "book";
  keywords: string[]; // matched against gap skill name (lowercase)
};

export const RESOURCE_LIBRARY: LibraryResource[] = [
  // ── Machine Learning / AI ────────────────────────────────────────────────────
  {
    id: "ml-coursera-andrew",
    title: "Machine Learning Specialization",
    creator: "Andrew Ng",
    platform: "Coursera",
    url: "https://www.coursera.org/specializations/machine-learning-introduction",
    is_free: false,
    duration_hint: "3 months",
    type: "course",
    keywords: ["machine learning", "ml", "supervised learning", "regression", "classification"],
  },
  {
    id: "dl-coursera-andrew",
    title: "Deep Learning Specialization",
    creator: "Andrew Ng / DeepLearning.AI",
    platform: "Coursera",
    url: "https://www.coursera.org/specializations/deep-learning",
    is_free: false,
    duration_hint: "5 months",
    type: "course",
    keywords: ["deep learning", "neural network", "cnn", "rnn", "lstm", "backpropagation"],
  },
  {
    id: "nnzts-karpathy",
    title: "Neural Networks: Zero to Hero (full playlist)",
    creator: "Andrej Karpathy",
    platform: "YouTube",
    url: "https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ",
    is_free: true,
    duration_hint: "12 hours",
    type: "video",
    keywords: ["neural network", "deep learning", "llm", "gpt", "backpropagation", "transformer"],
  },
  {
    id: "3b1b-neural",
    title: "Neural Networks (visual explainer)",
    creator: "3Blue1Brown",
    platform: "YouTube",
    url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi",
    is_free: true,
    duration_hint: "3 hours",
    type: "video",
    keywords: ["neural network", "gradient descent", "deep learning", "calculus", "math", "backpropagation"],
  },
  {
    id: "fastai-course",
    title: "Practical Deep Learning for Coders",
    creator: "fast.ai / Jeremy Howard",
    platform: "Free",
    url: "https://course.fast.ai",
    is_free: true,
    duration_hint: "Self-paced",
    type: "course",
    keywords: ["deep learning", "pytorch", "computer vision", "nlp", "machine learning", "fastai"],
  },
  {
    id: "statquest-ml",
    title: "StatQuest Machine Learning & Statistics",
    creator: "Josh Starmer",
    platform: "YouTube",
    url: "https://www.youtube.com/@statquest/playlists",
    is_free: true,
    duration_hint: "Ongoing",
    type: "video",
    keywords: ["statistics", "machine learning", "ml", "random forest", "pca", "bayesian", "probability"],
  },
  {
    id: "huggingface-course",
    title: "HuggingFace NLP Course",
    creator: "HuggingFace",
    platform: "Free",
    url: "https://huggingface.co/learn/nlp-course/chapter1/1",
    is_free: true,
    duration_hint: "Self-paced",
    type: "course",
    keywords: ["nlp", "transformers", "llm", "bert", "gpt", "huggingface", "language model", "fine-tuning"],
  },
  {
    id: "mlops-coursera",
    title: "Machine Learning Engineering for Production (MLOps)",
    creator: "Andrew Ng / DeepLearning.AI",
    platform: "Coursera",
    url: "https://www.coursera.org/specializations/machine-learning-engineering-for-production-mlops",
    is_free: false,
    duration_hint: "4 months",
    type: "course",
    keywords: ["mlops", "ml engineering", "production ml", "deployment", "monitoring", "data pipeline"],
  },
  {
    id: "kaggle-learn",
    title: "Kaggle Learn (free micro-courses)",
    creator: "Kaggle",
    platform: "Free",
    url: "https://www.kaggle.com/learn",
    is_free: true,
    duration_hint: "1-4 hours each",
    type: "course",
    keywords: ["data science", "python", "pandas", "machine learning", "sql", "feature engineering", "kaggle"],
  },
  {
    id: "deeplearning-shortcourses",
    title: "DeepLearning.AI Short Courses",
    creator: "DeepLearning.AI",
    platform: "Free",
    url: "https://www.deeplearning.ai/short-courses/",
    is_free: true,
    duration_hint: "1-2 hours each",
    type: "course",
    keywords: ["llm", "langchain", "prompt engineering", "rag", "agents", "chatgpt", "generative ai"],
  },

  // ── Python ───────────────────────────────────────────────────────────────────
  {
    id: "python-for-everybody",
    title: "Python for Everybody Specialization",
    creator: "Dr. Chuck / University of Michigan",
    platform: "Coursera",
    url: "https://www.coursera.org/specializations/python",
    is_free: false,
    duration_hint: "8 months",
    type: "course",
    keywords: ["python", "programming basics", "scripting"],
  },
  {
    id: "cs50p",
    title: "CS50's Introduction to Programming with Python",
    creator: "David Malan / Harvard",
    platform: "Free",
    url: "https://cs50.harvard.edu/python/2022/",
    is_free: true,
    duration_hint: "Self-paced",
    type: "course",
    keywords: ["python", "programming", "cs50", "beginner"],
  },
  {
    id: "corey-python",
    title: "Python Tutorials (full beginner → advanced)",
    creator: "Corey Schafer",
    platform: "YouTube",
    url: "https://www.youtube.com/playlist?list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU",
    is_free: true,
    duration_hint: "~30 hours",
    type: "video",
    keywords: ["python", "oop", "decorators", "generators", "scripting"],
  },
  {
    id: "sentdex-python",
    title: "Python for Finance / Data Science",
    creator: "sentdex",
    platform: "YouTube",
    url: "https://www.youtube.com/@sentdex",
    is_free: true,
    duration_hint: "Ongoing",
    type: "video",
    keywords: ["python", "data science", "finance", "matplotlib", "pandas", "numpy"],
  },

  // ── Data Science / Analytics ─────────────────────────────────────────────────
  {
    id: "google-data-analytics",
    title: "Google Data Analytics Professional Certificate",
    creator: "Google",
    platform: "Coursera",
    url: "https://www.coursera.org/professional-certificates/google-data-analytics",
    is_free: false,
    duration_hint: "6 months",
    type: "certification",
    keywords: ["data analytics", "sql", "tableau", "r", "spreadsheets", "data analysis"],
  },
  {
    id: "ibm-data-science",
    title: "IBM Data Science Professional Certificate",
    creator: "IBM",
    platform: "Coursera",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science",
    is_free: false,
    duration_hint: "11 months",
    type: "certification",
    keywords: ["data science", "python", "sql", "machine learning", "visualization", "jupyter"],
  },
  {
    id: "google-advanced-analytics",
    title: "Google Advanced Data Analytics Certificate",
    creator: "Google",
    platform: "Coursera",
    url: "https://www.coursera.org/professional-certificates/google-advanced-data-analytics",
    is_free: false,
    duration_hint: "6 months",
    type: "certification",
    keywords: ["statistics", "python", "regression", "machine learning", "data analytics"],
  },

  // ── Software Engineering / DSA ───────────────────────────────────────────────
  {
    id: "cs50-harvard",
    title: "CS50: Introduction to Computer Science",
    creator: "David Malan / Harvard",
    platform: "Free",
    url: "https://cs50.harvard.edu/x/",
    is_free: true,
    duration_hint: "Self-paced",
    type: "course",
    keywords: ["computer science", "algorithms", "c", "python", "web", "cs fundamentals"],
  },
  {
    id: "neetcode-dsa",
    title: "NeetCode DSA Course + Roadmap",
    creator: "NeetCode",
    platform: "YouTube",
    url: "https://www.youtube.com/@NeetCode",
    is_free: true,
    duration_hint: "Ongoing",
    type: "video",
    keywords: ["data structures", "algorithms", "leetcode", "dsa", "coding interview", "dynamic programming", "graphs"],
  },
  {
    id: "algorithms-sedgewick",
    title: "Algorithms, Part I",
    creator: "Robert Sedgewick / Princeton",
    platform: "Coursera",
    url: "https://www.coursera.org/learn/algorithms-part1",
    is_free: true,
    duration_hint: "6 weeks",
    type: "course",
    keywords: ["algorithms", "data structures", "java", "sorting", "graphs"],
  },
  {
    id: "primeagen-dsa",
    title: "Last Algorithms Course You'll Need",
    creator: "ThePrimeagen",
    platform: "YouTube",
    url: "https://www.youtube.com/@ThePrimeagen",
    is_free: true,
    duration_hint: "Ongoing",
    type: "video",
    keywords: ["algorithms", "data structures", "rust", "typescript", "performance", "system design"],
  },
  {
    id: "bytebytego-sd",
    title: "System Design Interview Series",
    creator: "ByteByteGo / Alex Xu",
    platform: "YouTube",
    url: "https://www.youtube.com/@ByteByteGo",
    is_free: true,
    duration_hint: "Ongoing",
    type: "video",
    keywords: ["system design", "distributed systems", "scalability", "architecture", "microservices"],
  },
  {
    id: "hussein-sd",
    title: "Fundamentals of Backend Engineering",
    creator: "Hussein Nasser",
    platform: "YouTube",
    url: "https://www.youtube.com/@hnasr",
    is_free: true,
    duration_hint: "Ongoing",
    type: "video",
    keywords: ["backend", "system design", "databases", "proxies", "networking", "api", "http"],
  },

  // ── Cloud / DevOps ───────────────────────────────────────────────────────────
  {
    id: "aws-clf-cert",
    title: "AWS Certified Cloud Practitioner",
    creator: "Amazon Web Services",
    platform: "Certification",
    url: "https://aws.amazon.com/certification/certified-cloud-practitioner/",
    is_free: false,
    duration_hint: "2-3 months prep",
    type: "certification",
    keywords: ["aws", "cloud", "cloud computing", "devops"],
  },
  {
    id: "aws-saa-cert",
    title: "AWS Solutions Architect Associate",
    creator: "Amazon Web Services",
    platform: "Certification",
    url: "https://aws.amazon.com/certification/certified-solutions-architect-associate/",
    is_free: false,
    duration_hint: "3-4 months prep",
    type: "certification",
    keywords: ["aws", "cloud architecture", "solutions architect", "cloud", "infrastructure"],
  },
  {
    id: "gcp-ace-cert",
    title: "Google Cloud Associate Cloud Engineer",
    creator: "Google Cloud",
    platform: "Certification",
    url: "https://cloud.google.com/certification/cloud-engineer",
    is_free: false,
    duration_hint: "3 months prep",
    type: "certification",
    keywords: ["google cloud", "gcp", "cloud", "kubernetes", "devops"],
  },
  {
    id: "gcp-data-cert",
    title: "Google Cloud Professional Data Engineer",
    creator: "Google Cloud",
    platform: "Certification",
    url: "https://cloud.google.com/certification/data-engineer",
    is_free: false,
    duration_hint: "3 months prep",
    type: "certification",
    keywords: ["gcp", "data engineering", "bigquery", "dataflow", "cloud"],
  },
  {
    id: "azure-fundamentals",
    title: "Microsoft Azure Fundamentals (AZ-900)",
    creator: "Microsoft",
    platform: "Certification",
    url: "https://learn.microsoft.com/en-us/certifications/azure-fundamentals/",
    is_free: false,
    duration_hint: "1-2 months prep",
    type: "certification",
    keywords: ["azure", "cloud", "microsoft cloud", "cloud computing"],
  },
  {
    id: "techworld-k8s",
    title: "Kubernetes & Docker Tutorial for Beginners",
    creator: "TechWorld with Nana",
    platform: "YouTube",
    url: "https://www.youtube.com/@TechWorldwithNana",
    is_free: true,
    duration_hint: "Ongoing",
    type: "video",
    keywords: ["kubernetes", "docker", "devops", "containers", "helm", "ci/cd", "microservices"],
  },
  {
    id: "networkchuck-net",
    title: "Networking + Cloud Labs",
    creator: "NetworkChuck",
    platform: "YouTube",
    url: "https://www.youtube.com/@NetworkChuck",
    is_free: true,
    duration_hint: "Ongoing",
    type: "video",
    keywords: ["networking", "linux", "cloud", "aws", "hacking", "cybersecurity", "vpn"],
  },
  {
    id: "google-cloud-skills",
    title: "Google Cloud Skills Boost (free labs)",
    creator: "Google Cloud",
    platform: "Free",
    url: "https://www.cloudskillsboost.google/",
    is_free: true,
    duration_hint: "Self-paced",
    type: "course",
    keywords: ["gcp", "google cloud", "bigquery", "vertex ai", "cloud run", "devops"],
  },
  {
    id: "aws-skillbuilder",
    title: "AWS Skill Builder (free learning plans)",
    creator: "Amazon Web Services",
    platform: "Free",
    url: "https://explore.skillbuilder.aws/learn",
    is_free: true,
    duration_hint: "Self-paced",
    type: "course",
    keywords: ["aws", "cloud", "lambda", "s3", "ec2", "devops"],
  },

  // ── Web / Frontend / Fullstack ────────────────────────────────────────────────
  {
    id: "meta-frontend",
    title: "Meta Front-End Developer Professional Certificate",
    creator: "Meta",
    platform: "Coursera",
    url: "https://www.coursera.org/professional-certificates/meta-front-end-developer",
    is_free: false,
    duration_hint: "7 months",
    type: "certification",
    keywords: ["frontend", "react", "javascript", "html", "css", "ui", "web development"],
  },
  {
    id: "meta-backend",
    title: "Meta Back-End Developer Professional Certificate",
    creator: "Meta",
    platform: "Coursera",
    url: "https://www.coursera.org/professional-certificates/meta-back-end-developer",
    is_free: false,
    duration_hint: "8 months",
    type: "certification",
    keywords: ["backend", "api", "django", "python", "databases", "rest", "web development"],
  },
  {
    id: "odin-project",
    title: "The Odin Project (full-stack free curriculum)",
    creator: "The Odin Project",
    platform: "Free",
    url: "https://www.theodinproject.com",
    is_free: true,
    duration_hint: "Self-paced",
    type: "course",
    keywords: ["web development", "html", "css", "javascript", "react", "node", "ruby", "fullstack"],
  },
  {
    id: "fullstack-open",
    title: "Full Stack Open (University of Helsinki)",
    creator: "University of Helsinki",
    platform: "Free",
    url: "https://fullstackopen.com/en/",
    is_free: true,
    duration_hint: "Self-paced",
    type: "course",
    keywords: ["react", "node", "graphql", "typescript", "testing", "fullstack", "javascript"],
  },
  {
    id: "traversy-web",
    title: "Web Development Crash Courses",
    creator: "Traversy Media",
    platform: "YouTube",
    url: "https://www.youtube.com/@TraversyMedia",
    is_free: true,
    duration_hint: "Ongoing",
    type: "video",
    keywords: ["javascript", "react", "node", "html", "css", "api", "web development", "express"],
  },
  {
    id: "fireship-web",
    title: "100 Seconds Series + Framework Deep Dives",
    creator: "Fireship",
    platform: "YouTube",
    url: "https://www.youtube.com/@Fireship",
    is_free: true,
    duration_hint: "Ongoing",
    type: "video",
    keywords: ["javascript", "typescript", "react", "firebase", "next.js", "web", "flutter", "rust"],
  },

  // ── Product / PM ──────────────────────────────────────────────────────────────
  {
    id: "google-pm-cert",
    title: "Google Project Management Professional Certificate",
    creator: "Google",
    platform: "Coursera",
    url: "https://www.coursera.org/professional-certificates/google-project-management",
    is_free: false,
    duration_hint: "6 months",
    type: "certification",
    keywords: ["project management", "pm", "agile", "scrum", "stakeholders", "planning"],
  },
  {
    id: "google-ux-cert",
    title: "Google UX Design Professional Certificate",
    creator: "Google",
    platform: "Coursera",
    url: "https://www.coursera.org/professional-certificates/google-ux-design",
    is_free: false,
    duration_hint: "6 months",
    type: "certification",
    keywords: ["ux", "user experience", "design thinking", "figma", "prototyping", "product design"],
  },

  // ── Security / Ethical Hacking ────────────────────────────────────────────────
  {
    id: "comptia-security",
    title: "CompTIA Security+ Certification",
    creator: "CompTIA",
    platform: "Certification",
    url: "https://www.comptia.org/certifications/security",
    is_free: false,
    duration_hint: "2-3 months prep",
    type: "certification",
    keywords: ["cybersecurity", "security", "network security", "cryptography", "soc", "compliance"],
  },
  {
    id: "networkchuck-security",
    title: "FREE Ethical Hacking Course",
    creator: "NetworkChuck",
    platform: "YouTube",
    url: "https://www.youtube.com/playlist?list=PLIhvC56v63IJIujb5cyE13oLuyORZpdkL",
    is_free: true,
    duration_hint: "~10 hours",
    type: "video",
    keywords: ["ethical hacking", "penetration testing", "cybersecurity", "kali linux", "security"],
  },

  // ── SQL / Databases ───────────────────────────────────────────────────────────
  {
    id: "sql-cs50",
    title: "CS50's Introduction to Databases with SQL",
    creator: "Harvard / CS50",
    platform: "Free",
    url: "https://cs50.harvard.edu/sql/2024/",
    is_free: true,
    duration_hint: "Self-paced",
    type: "course",
    keywords: ["sql", "database", "postgresql", "mysql", "sqlite", "queries", "data engineering"],
  },
  {
    id: "mode-sql",
    title: "Mode SQL Tutorial (interactive)",
    creator: "Mode Analytics",
    platform: "Free",
    url: "https://mode.com/sql-tutorial/",
    is_free: true,
    duration_hint: "~5 hours",
    type: "course",
    keywords: ["sql", "data analysis", "queries", "joins", "aggregations"],
  },

  // ── Generative AI / LLMs ──────────────────────────────────────────────────────
  {
    id: "prompt-engineering-dlai",
    title: "ChatGPT Prompt Engineering for Developers",
    creator: "DeepLearning.AI + OpenAI",
    platform: "Free",
    url: "https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/",
    is_free: true,
    duration_hint: "~2 hours",
    type: "course",
    keywords: ["prompt engineering", "llm", "chatgpt", "openai", "generative ai", "gpt"],
  },
  {
    id: "langchain-dlai",
    title: "LangChain for LLM Application Development",
    creator: "DeepLearning.AI",
    platform: "Free",
    url: "https://www.deeplearning.ai/short-courses/langchain-for-llm-application-development/",
    is_free: true,
    duration_hint: "~3 hours",
    type: "course",
    keywords: ["langchain", "llm", "rag", "agents", "generative ai", "llm apps"],
  },
  {
    id: "tensorflow-cert",
    title: "TensorFlow Developer Certificate",
    creator: "Google / TensorFlow",
    platform: "Certification",
    url: "https://www.tensorflow.org/certificate",
    is_free: false,
    duration_hint: "3 months prep",
    type: "certification",
    keywords: ["tensorflow", "deep learning", "neural network", "computer vision", "nlp"],
  },

  // ── Interview Prep ────────────────────────────────────────────────────────────
  {
    id: "neetcode-io",
    title: "NeetCode.io (structured Leetcode roadmap)",
    creator: "NeetCode",
    platform: "Free",
    url: "https://neetcode.io/roadmap",
    is_free: true,
    duration_hint: "Self-paced",
    type: "project",
    keywords: ["coding interview", "leetcode", "dsa", "algorithms", "interview prep"],
  },
  {
    id: "exercism",
    title: "Exercism (real code review + mentorship)",
    creator: "Exercism",
    platform: "Free",
    url: "https://exercism.org",
    is_free: true,
    duration_hint: "Self-paced",
    type: "project",
    keywords: ["coding practice", "python", "javascript", "go", "rust", "programming", "interview prep"],
  },
  {
    id: "github-oss",
    title: "GitHub Open Source Contribution Guide",
    creator: "GitHub",
    platform: "GitHub",
    url: "https://github.com/explore",
    is_free: true,
    duration_hint: "Ongoing",
    type: "project",
    keywords: ["open source", "github", "portfolio", "contribution", "real-world projects"],
  },
];

/**
 * Find the most relevant resources for a given skill name.
 * Returns up to `limit` results, ranked by keyword overlap.
 */
export function findResourcesForSkill(skillName: string, limit = 6): LibraryResource[] {
  const terms = skillName.toLowerCase().split(/[\s,/()-]+/).filter((t) => t.length > 2);

  const scored = RESOURCE_LIBRARY.map((r) => {
    const score = terms.reduce((acc, term) => {
      return acc + r.keywords.filter((kw) => kw.includes(term) || term.includes(kw)).length;
    }, 0);
    return { resource: r, score };
  });

  return scored
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((s) => s.resource);
}
